// Public Suffix List lookup (https://publicsuffix.org/list/), ICANN and private sections.
// Data: src/data/public-suffix.json, regenerated by scripts/sync-public-suffix.mjs.
// Each lookup follows the list's algorithm: an exception rule beats everything, otherwise
// the longest matching rule wins.
import { readFileSync } from 'node:fs'

const psl = JSON.parse(readFileSync(new URL('../data/public-suffix.json', import.meta.url), 'utf8'))

/** where the snapshot came from, for `validate` to print */
export const PUBLIC_SUFFIX_SOURCE = psl.source
export const PUBLIC_SUFFIX_ICANN_RULES = psl.icann
export const PUBLIC_SUFFIX_PRIVATE_RULES = psl.private

function lookup(rules) {
	const exact = new Set()
	const wildcard = new Set() // `*.b` stored as `b`
	const exception = new Set() // `!x.b` stored as `x.b`
	for(const rule of rules) {
		if(rule.startsWith('!')) {
			exception.add(rule.slice(1))
		} else if(rule.startsWith('*.')) {
			wildcard.add(rule.slice(2))
		} else {
			exact.add(rule)
		}
	}

	return domain => {
		const labels = domain.split('.')
		const n = labels.length
		let suffixLabels = 1 // the implicit `*` rule
		for(let k = 0; k < n; k++) {
			const candidate = labels.slice(k).join('.')
			if(exception.has(candidate)) {
				// an exception rule makes its parent the suffix, so `domain` is longer than it
				return false
			}

			if(exact.has(candidate)) {
				suffixLabels = Math.max(suffixLabels, n - k)
			}

			if(k + 1 < n && wildcard.has(labels.slice(k + 1).join('.'))) {
				suffixLabels = Math.max(suffixLabels, n - k)
			}
		}

		return suffixLabels >= n
	}
}

const isIcannSuffix = lookup(PUBLIC_SUFFIX_ICANN_RULES)
const isAnySuffix = lookup([...PUBLIC_SUFFIX_ICANN_RULES, ...PUBLIC_SUFFIX_PRIVATE_RULES])

/**
 * Which section makes `domain` (lowercase ASCII, no trailing dot) a public suffix: 'icann'
 * (including an unlisted TLD, which the implicit `*` rule makes a suffix), 'private' (it is
 * a suffix only because of a private-section rule such as github.io), or undefined.
 * @param {string} domain
 * @returns {'icann' | 'private' | undefined}
 */
export function publicSuffixSection(domain) {
	if(isIcannSuffix(domain)) {
		return 'icann'
	}

	return isAnySuffix(domain) ? 'private' : undefined
}

/**
 * true if `domain` is itself a public suffix, in either section
 * @param {string} domain
 * @returns {boolean}
 */
export function isPublicSuffix(domain) {
	return publicSuffixSection(domain) !== undefined
}
